server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/sistema_venta_ropa
    username: svr_user
    password: svr_pass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF

security:
  jwt:
    secret: ${SVR_JWT_SECRET:dev-secret-change-me}
    expiration-minutes: 240
